### ISSUE TITLE
Obiba repository out of date?

### ISSUE THREAD

**Issue by tombisho** [nparley/puppet-opal#4]
I am trying to build a test data machine using Puppet. I am using Ubuntu 16 and the associated branch but it looks like the code in question is in master too.

The error I see is:

Error: could not resolve http://pkg.obiba.org/obiba.org.key
Error: /Stage[main]/Opal::Repository/Apt::Source[obiba]/Apt::Key[Add key: B5719EDAB71FF8E6F6D008D95991857D7A49E499 from Apt::Source obiba]/Apt_key[Add key: B5719EDAB71FF8E6F6D008D95991857D7A49E499 from Apt::Source obiba]/ensure: change from 'absent' to 'present' failed: could not resolve http://pkg.obiba.org/obiba.org.key

I think this is the old repository for Obiba. The new repository details can be found here:

https://www.obiba.org/pages/pkg/

Of course, this comes with usual caveats that I might have done something wrong, so I'm sorry if I have missed something obvious...

**Comment by StuartWheater** [comment]
Please can you confirm you are using puppet directly, not via Vagrant.
If you are using Vagrant, which VagrantFile are you using?

**Comment by tombisho** [comment]
Hi Stuart, I have built my own VM so not using Vagrant.

I think I have solved the problem - unfortunately it was due to me forgetting to use the ubuntu16 branch for one of the steps :(

The machine is currently building and has got a lot further than last time, so hopefully I can close this shortly...

**Comment by StuartWheater** [comment]
Please could you check you are using the "ubuntu16" branch.

**Comment by tombisho** [comment]
:) exactly!

**Comment by tombisho** [comment]
As expected, the problem was not using the ubuntu16 branch. Sorry!
